"""Add user/audit log/code/file tables

Revision ID: 7c0d5ddc997b
Revises: 060ea8eea4c9
Create Date: 2022-05-04 17:35:26.648868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0d5ddc997b'
down_revision = '060ea8eea4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Unicode(length=256), nullable=False),
    sa.Column('details', sa.Unicode(length=1024), nullable=False),
    sa.Column('bit_id', sa.Integer(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('when', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Unicode(length=16384), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('File',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=False),
    sa.Column('bit_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.Column('mod', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.add_column('Bit', sa.Column('archived', sa.Boolean(), nullable=True))
    op.drop_column('Bit', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bit', sa.Column('code', sa.VARCHAR(), nullable=False))
    op.drop_column('Bit', 'archived')
    op.drop_table('User')
    op.drop_table('File')
    op.drop_table('Code')
    op.drop_table('Audit')
    # ### end Alembic commands ###
